---
name: aur-publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: tenv-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Release tenv ${{ github.ref_name }}"
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

      - name: Create version release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "PKGBUILD"
          generateReleaseNotes: true
