---
name: PKGBUILD PR Creator

on:
  workflow_dispatch:

jobs:
  VersionUpdater:
    runs-on: ubuntu-latest
    name: Version Updater
    steps:
      - uses: actions/checkout@v4

      - uses: cardinalby/git-get-release-action@v1
        name: Get tenv version
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: tofuutils/tenv
          latest: true
        id: tf_version
      - uses: cardinalby/git-get-release-action@v1
        name: Get this repo's version
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
        id: repo_version

      - name: Display tenv Version Information
        run: |
          echo "tenv release: ${{ steps.tf_version.outputs.tag_name }}"
          echo "AUR package release: ${{ steps.repo_version.outputs.tag_name }}"

      - name: Sanity check run only if version is different
        run: echo "The tenv version differs from what is pinned in the AUR package! We should make a new release!"
        if: ${{ steps.tf_version.outputs.tag_name != steps.repo_version.outputs.tag_name }}

      # - Get Linux release URLs for all supported Linux architectures
      - name: Get Linux release URLs
        run: |
          echo '${{ steps.tf_version.outputs.assets }}' | jq .
      # - Get Linux release checksums file
      # - Extract checksums from file
      # - Generate new PKGBUILD file
      # - Create PR
