---
name: PKGBUILD PR Creator

on:
  workflow_dispatch:

jobs:
  VersionUpdater:
    runs-on: ubuntu-latest
    name: Version Updater
    steps:
      - uses: actions/checkout@v4

      - uses: cardinalby/git-get-release-action@v1
        name: Get tenv version
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo: tofuutils/tenv
          latest: true
        id: tf_version
      - uses: cardinalby/git-get-release-action@v1
        name: Get this repo's version
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
        id: repo_version

      - name: Display tenv Version Information
        run: |
          echo "tenv release: ${{ steps.tf_version.outputs.tag_name }}"
          echo "AUR package release: ${{ steps.repo_version.outputs.tag_name }}"
